"""role column

Revision ID: 5617f3643b05
Revises: 
Create Date: 2020-05-19 18:02:34.096725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5617f3643b05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin__headquaters', sa.Column('role', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin__headquaters', 'role')
    # ### end Alembic commands ###
