"""export column

Revision ID: e7925469fab2
Revises: 5617f3643b05
Create Date: 2020-05-20 21:21:01.378940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7925469fab2'
down_revision = '5617f3643b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApprovedExports', sa.Column('date', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ApprovedExports', 'date')
    # ### end Alembic commands ###
